### ISSUE TITLE
No subtitles for the new video

### ISSUE THREAD

**Issue by ElissaCong** [gfw-breaker/raw-subtitles#1]
Hi, the new video from the tianliang channel doesn't have any subtitle file uploaded.

**Comment by labour-camp** [comment]
@gfw-breaker  It will be uploaded in 1 hours after the video is published.
I found you forked this repo, I think you were trying to find it in your repo, right ?

**Comment by gfw-breaker** [comment]
@ElissaCong The subtitle will be uploaded to this repo in 1 hour after the video published.
I found you forked this repo, you should try to find the subtitle in my repo rather than yours.

**Comment by gfw-breaker** [comment]
@ElissaCong  Yes, indeed. I found a bug, and fixed it already.

**Comment by ElissaCong** [comment]
thanks for your job. Now, there are some other troubles now. Maybe you can also see that. The subtitles from the earlier videos are no longer readable. Could you please check it out? Thanks a lot!!!

**Comment by gfw-breaker** [comment]
@ElissaCong  Fixed. Thanks for reporting bugs  :-）

**Comment by ElissaCong** [comment]
^-^ great! Thank you!
