### ISSUE TITLE
the tiangliang channel stopped to update

### ISSUE THREAD

**Issue by ElissaCong** [gfw-breaker/raw-subtitles#2]
Hi, since 4. July the tianliang channel doesn't upload any new videos. Could you please check it out? Thanks a lot.

**Comment by gfw-breaker** [comment]
Hello, 

I found the title of the video on 4th June is too long, and as file name is the same as the title, so the tool reported ```ERROR: unable to open for writing: [Errno 36] File name too long:```
I will use a workaround for the moment, the file name will be original file name when it was uploaded.
And try to fix this.
