### ISSUE TITLE
請幫忙加一個頻道

### ISSUE THREAD

**Issue by ElissaCong** [gfw-breaker/raw-subtitles#3]
您好~~ 謝謝您一直以來的及時支援。現在節目部又開通一個新的頻道《大樹教練》，不知道您是否方便把這個頻道也加入到您的這個字幕自動生成工具裏來？

這裡是頻道的官方帳號鏈接：
https://www.youtube.com/channel/UC3WwtORvtc2O6hoFgOQld4A
https://www.youtube.com/channel/UC3WwtORvtc2O6hoFgOQld4A/videos

非常感謝~~

子悠

**Comment by gfw-breaker** [comment]
您好，
已经添加。为了方便用正体汉字的朋友修正字幕，特添加正体字幕。乐见优秀中文自媒体遍地开花~。
BR.

**Comment by ElissaCong** [comment]
太棒了！謝謝~~
